### PR TITLE
Created LICENSE Header

### PR DESCRIPTION
**Pull request by Crusherbolt**
Created LICENSE Header

### CODE REVIEW

**Comment by Crusherbolt** [comment]
hwtesh.sh is for Add an optional command line argument to test everything at once.

**Comment by TechnologyClassroom** [comment]
I commented on this pull request here: https://github.com/TechnologyClassroom/HardwareTest/issues/5#issuecomment-2424971805

**Comment by MaiHistoryCompanyLimited** [comment]
Update hwtest.sh #8

**Comment by TechnologyClassroom** [comment]
I'm happy to work with you on these three PRs that you closed if you want to continue.

**Pull request closed without merging**
